export enum E_CONTROLE_INTEGRACAO {
  BANDEJA = "Bandeja",
  BANDEJA_PRODUTO = "BandejaProduto",
  BANDEJA_VENDEDOR = "BandejaVendedor",
  BANDEJA_VENDEDOR_PRODUTO = "BandejaVendedorProduto",
  FRETE_DESCONTO_ACORDADO = "Frete",
  CAIXA = "Caixa",
  CARTEIRA_CLIENTE = "Cliente",
  CATALOGO = "Catalogo",
  DISPLAY = "Display",
  FILTRO_LINHA = "FiltroLinha",
  FILTRO_SUBLINHA = "FiltroSublinha",
  FILTRO_SUBGRUPO = "FiltroSubgrupo",
  FILTRO_MARCA = "FiltroMarca",
  FILTRO_ORIGEM = "FiltroOrigem",
  FRETE = "Frete",
  MECANISMO = "Mecanismo",
  MOSTRADOR = "Mostrador",
  NOVO_PEDIDO = "NovoPedido",
  OUTRO = "Outro",
  PAGAMENTO_CLIENTE = "PagamentoCliente",
  PAGAMENTO = "Pagamento",
  PEDIDO = "Pedido",
  PRODUTO = "Produto",
  PULSEIRA = "Pulseira",
  PULSEIRA_MATERIAL = "PulseiraMaterial",
  PULSEIRA_TAMANHO = "PulseiraTamanho",
  REPRESENTANTE_PRODUTO = "RepresentanteProduto",
  REPRESENTANTE = "Representante",
  TABELA_PRECO = "TabelaPreco",
  TABELA_PRECO_PRODUTO = "TabelaPrecoProduto",
  SINALIZADORES = "Sinalizadores",
  QUEM_COMPROU_CLIENTE = "QuemComprouCliente",
  EXPOSITOR = "Expositor",
  PEDIDO_MINIMO = "PedidoMinimo",
  HISTORICO_COMPRA_CLIENTE = "HistoricoCompraCliente",
}

export const CONTROLE_INTEGRACAO = [
  {
    codigo: E_CONTROLE_INTEGRACAO.BANDEJA,
    endpoint: "api/bandeja",
    descricao: "Controle de Integração - Bandeja",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.BANDEJA_PRODUTO,
    endpoint: "api/bandeja/produto",
    descricao: "Controle de Integração - Bandeja Produto",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.BANDEJA_VENDEDOR,
    endpoint: "api/bandejavendedor",
    descricao: "Controle de Integração - Bandeja Vendedor",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.BANDEJA_VENDEDOR_PRODUTO,
    endpoint: "api/bandejavendedor/produto",
    descricao: "Controle de Integração - Bandeja Vendedor Produto",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.FRETE_DESCONTO_ACORDADO,
    endpoint: "api/Frete",
    descricao: "Controle de Integração - Frete Desconto Acordado",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.CAIXA,
    endpoint: "api/caixa/material",
    descricao: "Controle de Integração - Caixa",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.CARTEIRA_CLIENTE,
    endpoint: "api/carteiracliente",
    descricao: "Controle de Integração - Carteira Cliente",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.CATALOGO,
    endpoint: "api/catalogo",
    descricao: "Controle de Integração - Catalogo",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.DISPLAY,
    endpoint: "api/display",
    descricao: "Controle de Integração - Display",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.FILTRO_LINHA,
    endpoint: "api/filtro/linha",
    descricao: "Controle de Integração - Filtro Linha",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.FILTRO_SUBLINHA,
    endpoint: "api/filtro/sublinha",
    descricao: "Controle de Integração - Filtro Sublinha",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.FILTRO_SUBGRUPO,
    endpoint: "api/filtro/subgrupo",
    descricao: "Controle de Integração - Filtro Subgrupo",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.FILTRO_MARCA,
    endpoint: "api/filtro/marca",
    descricao: "Controle de Integração - Filtro Marca",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.FILTRO_ORIGEM,
    endpoint: "api/marca",
    descricao: "Controle de Integração - Filtro Origem",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.FRETE,
    endpoint: "api/frete",
    descricao: "Controle de Integração - Frete",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.MECANISMO,
    endpoint: "api/mecanismo",
    descricao: "Controle de Integração - Mecanismo",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.MOSTRADOR,
    endpoint: "api/mostrador",
    descricao: "Controle de Integração - Mostrador",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.NOVO_PEDIDO,
    endpoint: null,
    descricao: "Controle de Integração - Novo Pedido",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.OUTRO,
    endpoint: "api/outro",
    descricao: "Controle de Integração - Outro",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.PAGAMENTO_CLIENTE,
    endpoint: "api/pagamento/cliente",
    descricao: "Controle de Integração - Pagamento Cliente",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.PAGAMENTO,
    endpoint: "api/pagamento",
    descricao: "Controle de Integração - Pagamento",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.PEDIDO,
    endpoint: "api/pedido",
    descricao: "Controle de Integração - Pedido",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.PRODUTO,
    endpoint: "api/produtotipo",
    descricao: "Controle de Integração - Produto",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.PULSEIRA,
    endpoint: "api/pulseira",
    descricao: "Controle de Integração - Pulseira",
    pageSize: 100,
    dataAtualizacao: null,
  },

  {
    codigo: E_CONTROLE_INTEGRACAO.REPRESENTANTE,
    endpoint: "api/representante",
    descricao: "Controle de Integração - Representante",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.TABELA_PRECO_PRODUTO,
    endpoint: "api/tabelapreco/produto",
    descricao: "Controle de Integração - Tabela Preço Produto",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.SINALIZADORES,
    endpoint: "api/sinalizador",
    descricao: "Controle de Integração - Sinalizador",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.QUEM_COMPROU_CLIENTE,
    endpoint: "api/quemcomproucliente",
    descricao: "Controle de Integração - Quem Comprou Cliente",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.EXPOSITOR,
    endpoint: "api/expositor",
    descricao: "Controle de Integração - Expositor",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.HISTORICO_COMPRA_CLIENTE,
    endpoint: "api/historicocompracliente",
    descricao: "Controle de Integração - Historico Compra Cliente",
    pageSize: 100,
    dataAtualizacao: null,
  },
  {
    codigo: E_CONTROLE_INTEGRACAO.PEDIDO_MINIMO,
    endpoint: "api/pedidominimo",
    descricao: "Controle de Integração - Pedido Minimo",
    pageSize: 100,
    dataAtualizacao: null,
  },
];
