export const createCatalogoTable = `
  CREATE TABLE IF NOT EXISTS Catalogo (
    codigo TEXT,
    tipoProduto TEXT,
    nomeEcommerce TEXT,
    filialMarca TEXT,
    codigoMarca TEXT,
    descricaoMarca TEXT,
    garantia TEXT,
    codigoBarra TEXT,
    ncm TEXT,
    precoUnitario REAL,
    precoUnitarioComIPI REAL,
    precoComIPI REAL,
    descricaoComercial TEXT,
    descricaoTecnica TEXT,
    tamanhoCaixa TEXT,
    peso REAL,
    fecho TEXT,
    resistenciaAgua TEXT,
    materialPulseira TEXT,
    materialCaixa TEXT,
    tipoFundo TEXT,
    funcaoMecanismo TEXT,
    filialSubGrupo TEXT,
    codigoSubGrupo TEXT,
    descricaoSubGrupo TEXT,
    grupoSubGrupo TEXT,
    filialLinha TEXT,
    codigoLinha TEXT,
    descricaoLinha TEXT,
    subGrupoLinha TEXT,
    display TEXT,
    flagBestSeller TEXT,
    flagComKit TEXT,
    flagLancamento TEXT,
    flagMonteSeuKit TEXT,
    flagPreVenda TEXT,
    genero TEXT,
    nacionalImportado TEXT,
    flagRetorno TEXT,
    exclusividadeVendedor TEXT,
    espessuraCaixa TEXT,
    tamanhoPulseira TEXT,
    quantidadeEstoquePA INTEGER,
    grupo TEXT,
    corMostrador TEXT,
    corPulseira TEXT,
    precoPromo REAL,
    descontoPromo REAL,
    precoSemIPI REAL,
    dataPrevistaPA TEXT,
    banho TEXT,
    corCaixa TEXT,
    ipi REAL,
    filialOrigem TEXT,
    codigoOrigem TEXT,
    descricaoOrigem TEXT,
    filialSubLinha TEXT,
    codigoSubLinha TEXT,
    descricaoSubLinha TEXT,
    linhaSubLinha TEXT,
    filialTipoProduto TEXT,
    codigoTipoProduto TEXT,
    descricaoTipoProduto TEXT,
    imagens TEXT,
    sinalizadores TEXT,
    codigoBarraFeiras TEXT
);

`;

export const deleteCatalogoData = `
  DELETE FROM Catalogo;
`;

export const dropCatalogoData = `
DROP TABLE IF EXISTS Catalogo;
`;

export const insertCatalogoData = `
INSERT INTO Catalogo (
    codigo,
    tipoProduto,
    nomeEcommerce,
    filialMarca,
    codigoMarca,
    descricaoMarca,
    garantia,
    codigoBarra,
    ncm,
    precoUnitario,
    precoUnitarioComIPI,
    precoComIPI,
    descricaoComercial, 
    descricaoTecnica,
    tamanhoCaixa,
    peso,
    fecho,
    resistenciaAgua,
    materialPulseira,
    materialCaixa,
    tipoFundo,
    funcaoMecanismo,
    filialSubGrupo, 
    codigoSubGrupo,
    descricaoSubGrupo,
    grupoSubGrupo,
    filialLinha,
    codigoLinha,
    descricaoLinha,
    subGrupoLinha,
    display,
    flagBestSeller,
    flagComKit, 
    flagLancamento,
    flagMonteSeuKit,
    flagPreVenda,
    genero,
    nacionalImportado,
    flagRetorno,
    exclusividadeVendedor,
    espessuraCaixa,
    tamanhoPulseira,
    quantidadeEstoquePA, 
    grupo,
    corMostrador,
    corPulseira,
    precoPromo,
    descontoPromo,
    precoSemIPI,
    dataPrevistaPA,
    banho,
    corCaixa,
    ipi, 
    filialOrigem,
    codigoOrigem,
    descricaoOrigem,
    filialSubLinha,
    codigoSubLinha,
    descricaoSubLinha,
    linhaSubLinha,
    filialTipoProduto,
    codigoTipoProduto,
    descricaoTipoProduto, 
    imagens,
    sinalizadores,
    codigoBarraFeiras
  ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
`;
