export const createNovoPedidoTable = `
  CREATE TABLE IF NOT EXISTS NovoPedido (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    codigoMobile TEXT,
    razaoSocial TEXT,
    nomeEcommerce TEXT,
    numeroPedido TEXT,
    pedidoTechnosPlus TEXT,
    pedidoInterno TEXT,
    plataforma TEXT,
    clienteId TEXT NOT NULL,
    cpfCnpj TEXT,  -- Alinhado com o JSON
    representanteId TEXT,
    representanteCreateId TEXT,  -- Novo campo
    quantidadeItens INTEGER,
    quantidadePecas INTEGER,
    valorTotal REAL,
    valorTotalComIPI REAL,
    valorTotalDescontos REAL,
    formaPagamento INTEGER,
    diasPrimeiroVencimento INTEGER,
    quantidadeDuplicata INTEGER,
    informacaoComplementar TEXT,
    percentualDeFrete REAL,
    percentualDeDesconto REAL,
    tipoPagamento INTEGER,
    local TEXT,
    dataPedidoSaldo TEXT,
    quebraPreVenda BOOLEAN,
    dataPrevistaPA TEXT,
    tipoPedido TEXT,
    motivoBonificacao INTEGER,
    descricaoMotivoBonificacao INTEGER,
    enderecoEntrega TEXT,
    numeroEntrega TEXT,
    cepEntrega TEXT,
    bairroEntrega TEXT,
    complementoEntrega TEXT,
    alterarEnderecoDeEntrega TEXT,
    tipoLogradouroEntrega TEXT,
    pedidoContaEOrdem BOOLEAN,
    estadoEntrega TEXT,
    ufEntrega TEXT,
    municipioEntrega TEXT,
    tabelaDePrecoId TEXT,
    status TEXT,
    statusDescricao TEXT,
    ganhadores TEXT,
    pedidoSaldo TEXT,
    dataCriacao TEXT,
    lojas TEXT,
    produtos TEXT,
    meiosPagamento TEXT,
    selectedTabelaPreco TEXT
);
`;

export const deleteNovoPedidoData = `DELETE FROM NovoPedido;`;

export const insertNovoPedidoData = `
  INSERT INTO NovoPedido (
  codigoMobile,
    razaoSocial,
    nomeEcommerce,
    numeroPedido,
    pedidoTechnosPlus,
    pedidoInterno,
    plataforma,
    clienteId,
    cpfCnpj,
    representanteId,
    quantidadeItens,
    quantidadePecas,
    valorTotal,
    valorTotalComIPI,
    valorTotalDescontos,
    formaPagamento,
    diasPrimeiroVencimento,
    quantidadeDuplicata,
    informacaoComplementar,
    percentualDeFrete,
    percentualDeDesconto,
    tipoPagamento,
    local,
    dataPedidoSaldo,
    quebraPreVenda,
    dataPrevistaPA,
    tipoPedido,
    motivoBonificacao,
    descricaoMotivoBonificacao,
    enderecoEntrega,
    numeroEntrega,
    cepEntrega,
    bairroEntrega,
    complementoEntrega,
    alterarEnderecoDeEntrega,
    tipoLogradouroEntrega,
    pedidoContaEOrdem,
    estadoEntrega,
    ufEntrega,
    municipioEntrega,
    tabelaDePrecoId,
    status,
    statusDescricao,
    ganhadores,
    pedidoSaldo,
    dataCriacao,
    lojas,
    produtos,
    meiosPagamento,
    selectedTabelaPreco
  ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
`;
