export const createPedidoSincronizadoTable = `
  CREATE TABLE IF NOT EXISTS PedidoSincronizado (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    codigoMobile TEXT,
    alterarEnderecoDeEntrega TEXT,
    bairroEntrega TEXT,
    cepEntrega TEXT,
    clienteId TEXT NOT NULL,
    complementoEntrega TEXT,
    dataPedidoSaldo TEXT,
    dataPrevistaPA TEXT,
    descricaoMotivoBonificacao TEXT,
    diasPrimeiroVencimento TEXT,
    enderecoEntrega TEXT,
    estadoEntrega TEXT,
    ganhadores TEXT,
    motivoBonificacao TEXT,
    municipioEntrega TEXT,
    numeroEntrega TEXT,
    numeroPedido TEXT,
    percentualDeDesconto REAL,
    plataforma TEXT,
    quantidadeItens INTEGER,
    quantidadePecas INTEGER,
    quebraPreVenda BOOLEAN,
    representanteCreateId TEXT,
    representanteId TEXT,
    tabelaDePrecoId TEXT,
    tipoLogradouroEntrega TEXT,
    tipoPedido TEXT,
    dataCriacao TEXT,
    dataSincronizacao TEXT,
    statusCodigo INTEGER,
    statusDescricao TEXT,
    valorTotal REAL,
    valorTotalComIPI REAL,
    valorTotalDescontos REAL,
    produtos TEXT,
    meiosPagamento TEXT
);
`;

export const deletePedidoSincronizadoData = `DELETE FROM PedidoSincronizado;`;

export const dropPedidoSincronizadoData = `DROP TABLE IF EXISTS PedidoSincronizado;`;

export const insertPedidoSincronizadoData = `
  INSERT INTO PedidoSincronizado (
    codigoMobile,
    alterarEnderecoDeEntrega,
    bairroEntrega,
    cepEntrega,
    clienteId,
    complementoEntrega,
    dataPedidoSaldo,
    dataPrevistaPA,
    descricaoMotivoBonificacao,
    diasPrimeiroVencimento,
    enderecoEntrega,
    estadoEntrega,
    ganhadores,
    motivoBonificacao,
    municipioEntrega,
    numeroEntrega,
    numeroPedido,
    percentualDeDesconto,
    plataforma,
    quantidadeItens,
    quantidadePecas,
    quebraPreVenda,
    representanteCreateId,
    representanteId,
    tabelaDePrecoId,
    tipoLogradouroEntrega,
    tipoPedido,
    dataCriacao,
    dataSincronizacao,
    statusCodigo,
    statusDescricao,
    valorTotal,
    valorTotalComIPI,
    valorTotalDescontos,
    produtos,
    meiosPagamento
  ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
`;
