export const createTabelaPrecoTable = `
  CREATE TABLE IF NOT EXISTS TabelaPreco (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tabelaPrecoCodigo TEXT,
  tabelaPrecoDescricao TEXT,
  tabelaPrecoDataInicioVigencia TEXT,
  tabelaPrecoHoraInicioVigencia TEXT,
  tabelaPrecoDataFimVigencia TEXT,
  tabelaPrecoHoraFimVigencia TEXT,
  tabelaPrecoCondicaoPagamento TEXT,
  tabelaPrecoTipoHora TEXT,
  tabelaPrecoAtivo TEXT,
  tabelaPrecoFilial TEXT,
  tabelaPrecoFilialPublicacao TEXT,
  tabelaPrecoCodigoPublicacao TEXT,
  tabelaPrecoFlagEC TEXT,
  tabelaPrecoDataExportacaoEC TEXT,
  tabelaPrecoSequenciaExportacaoEC TEXT,
  tabelaPrecoMensagemExportacao TEXT,
  tabelaPrecoHoraExportacao TEXT,
  produtoFilial TEXT,
  produtoCodigoItem TEXT,
  produtoCodigo TEXT,
  produtoPrecoVenda INTEGER,
  produtoValorDesconto INTEGER,
  produtoPercentualDesconto INTEGER,
  produtoAtivo TEXT,
  produtoFrete INTEGER,
  produtoEstado TEXT,
  produtoTipoOperacao TEXT,
  produtoQuantidadeLote INTEGER,
  produtoIndicadorLote TEXT,
  produtoMoeda INTEGER,
  produtoDataVigencia TEXT,
  produtoGrupo TEXT,
  produtoReferenciaGrade TEXT,
  produtoPrecoMaximo INTEGER,
  produtoItemGrupo TEXT,
  produtoDataUltimaMovimentacao TEXT,
  produtoHoraUltimaMovimentacao TEXT,
  produtoDataExportacaoEC TEXT,
  produtoSequenciaExportacaoEC TEXT,
  produtoUsuarioGeracaoInicial TEXT,
  produtoUsuarioGeracaoAtualizacao TEXT,
  produtoMensagemExportacao TEXT,
  produtoHoraExportacao TEXT,
  produtoEnvioEC TEXT,
  produtoDataAlteracao TEXT,
  produtoHoraAlteracao TEXT,
  produtoHoraExportacaoFinal TEXT,
  produtoTipoPreco TEXT,
  produtoPrecoUnitario INTEGER
  );
`;

export const deleteTabelaPrecoData = `DELETE FROM TabelaPreco;`;

export const dropTabelaPrecoTable = `DROP TABLE IF EXISTS TabelaPreco;`;

export const insertTabelaPrecoData = `
  INSERT INTO TabelaPreco (
  tabelaPrecoCodigo,
  tabelaPrecoDescricao,
  tabelaPrecoDataInicioVigencia,
  tabelaPrecoHoraInicioVigencia,
  tabelaPrecoDataFimVigencia,
  tabelaPrecoHoraFimVigencia,
  tabelaPrecoCondicaoPagamento,
  tabelaPrecoTipoHora,
  tabelaPrecoAtivo,
  tabelaPrecoFilial,
  tabelaPrecoFilialPublicacao,
  tabelaPrecoCodigoPublicacao,
  tabelaPrecoFlagEC,
  tabelaPrecoDataExportacaoEC,
  tabelaPrecoSequenciaExportacaoEC,
  tabelaPrecoMensagemExportacao,
  tabelaPrecoHoraExportacao,
  produtoFilial,
  produtoCodigoItem,
  produtoCodigo,
  produtoPrecoVenda,
  produtoValorDesconto,
  produtoPercentualDesconto,
  produtoAtivo,
  produtoFrete,
  produtoEstado,
  produtoTipoOperacao,
  produtoQuantidadeLote,
  produtoIndicadorLote,
  produtoMoeda,
  produtoDataVigencia,
  produtoGrupo,
  produtoReferenciaGrade,
  produtoPrecoMaximo,
  produtoItemGrupo,
  produtoDataUltimaMovimentacao,
  produtoHoraUltimaMovimentacao,
  produtoDataExportacaoEC,
  produtoSequenciaExportacaoEC,
  produtoUsuarioGeracaoInicial,
  produtoUsuarioGeracaoAtualizacao,
  produtoMensagemExportacao,
  produtoHoraExportacao,
  produtoEnvioEC,
  produtoDataAlteracao,
  produtoHoraAlteracao,
  produtoHoraExportacaoFinal,
  produtoTipoPreco,
  produtoPrecoUnitario
  ) 
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
`;
