export const createTabelaPrecoProdutoTable = `
  CREATE TABLE IF NOT EXISTS TabelaPrecoProduto (
    codigo TEXT,
    prefixoReferencia TEXT,
    tipoProduto TEXT,
    nomeEcommerce TEXT,
    filialMarca TEXT,
    codigoMarca TEXT,
    descricaoMarca TEXT,
    garantia TEXT,
    codigoBarra TEXT,
    ncm TEXT,
    precoUnitario REAL,
    precoUnitarioRelacaoEstoque REAL,
    desconto REAL,
    precoComIPI REAL,
    descricaoComercial TEXT,
    tamanhoCaixa REAL,
    peso REAL,
    fecho TEXT,
    resistenciaAgua TEXT,
    materialPulseira TEXT,
    materialCaixa TEXT,
    tipoFundo TEXT,
    funcaoMecanismo TEXT,
    filialSubGrupo TEXT,
    codigoSubGrupo TEXT,
    descricaoSubGrupo TEXT,
    grupoSubGrupo TEXT,
    filialLinha TEXT,
    codigoLinha TEXT,
    descricaoLinha TEXT,
    subGrupoLinha TEXT,
    display TEXT,
    flagBestSeller TEXT,
    flagComKit TEXT,
    flagLancamento TEXT,
    flagMonteSeuKit TEXT,
    flagPreVenda TEXT,
    genero TEXT,
    nacionalImportado TEXT,
    flagRetorno TEXT,
    exclusividadeVendedor TEXT,
    espessuraCaixa REAL,
    tamanhoPulseira REAL,
    quantidadeEstoquePA INTEGER,
    grupo TEXT,
    corMostrador TEXT,
    corPulseira TEXT,
    precoPromo REAL,
    descontoPromo REAL,
    precoSemIPI REAL,
    dataPrevistaPA TEXT,
    banho TEXT,
    corCaixa TEXT,
    ipi REAL,
    filialOrigem TEXT,
    codigoOrigem TEXT,
    descricaoOrigem TEXT,
    filialSubLinha TEXT,
    codigoSubLinha TEXT,
    descricaoSubLinha TEXT,
    linhaSubLinha TEXT,
    filialTipoProduto TEXT,
    codigoTipoProduto TEXT,
    descricaoTipoProduto TEXT,
    codigoTabelaPreco TEXT,
    filial TEXT,
    codigoItem TEXT,
    precoVenda REAL,
    valorDesconto REAL,
    percentualDesconto REAL,
    ativo TEXT,
    frete REAL,
    estado TEXT,
    tipoOperacao TEXT,
    quantidadeLote INTEGER,
    indicadorLote TEXT,
    moeda REAL,
    dataVigencia TEXT,
    referenciaGrade TEXT,
    precoMaximo REAL,
    itemGrupo TEXT,
    dataUltimaMovimentacao TEXT,
    horaUltimaMovimentacao TEXT,
    dataExportacaoEC TEXT,
    sequenciaExportacaoEC TEXT,
    usuarioGeracaoInicial TEXT,
    usuarioGeracaoAtualizacao TEXT,
    mensagemExportacao TEXT,
    horaExportacao TEXT,
    envioEC TEXT,
    dataAlteracao TEXT,
    horaAlteracao TEXT,
    horaExportacaoFinal TEXT,
    tipoPreco TEXT,
    imagens TEXT,
    sinalizadores TEXT,
    codigoBarraFeiras TEXT
  );
`;

export const deleteTabelaPrecoProdutoData = `DELETE FROM TabelaPrecoProduto;`;

export const dropTabelaPrecoProdutoTable = `DROP TABLE IF EXISTS TabelaPrecoProduto;`;

export const insertTabelaPrecoProdutoData = `
  INSERT INTO TabelaPrecoProduto (
    codigo,
    prefixoReferencia,
    tipoProduto,
    nomeEcommerce,
    filialMarca,
    codigoMarca,
    descricaoMarca,
    garantia,
    codigoBarra,
    ncm,
    precoUnitario,
    precoUnitarioRelacaoEstoque,
    desconto,
    precoComIPI,
    descricaoComercial,
    tamanhoCaixa,
    peso,
    fecho,
    resistenciaAgua,
    materialPulseira,
    materialCaixa,
    tipoFundo,
    funcaoMecanismo,
    filialSubGrupo,
    codigoSubGrupo,
    descricaoSubGrupo,
    grupoSubGrupo,
    filialLinha,
    codigoLinha,
    descricaoLinha,
    subGrupoLinha,
    display,
    flagBestSeller,
    flagComKit,
    flagLancamento,
    flagMonteSeuKit,
    flagPreVenda,
    genero,
    nacionalImportado,
    flagRetorno,
    exclusividadeVendedor,
    espessuraCaixa,
    tamanhoPulseira,
    quantidadeEstoquePA,
    grupo,
    corMostrador,
    corPulseira,
    precoPromo,
    descontoPromo,
    precoSemIPI,
    dataPrevistaPA,
    banho,
    corCaixa,
    ipi,
    filialOrigem,
    codigoOrigem,
    descricaoOrigem,
    filialSubLinha,
    codigoSubLinha,
    descricaoSubLinha,
    linhaSubLinha,
    filialTipoProduto,
    codigoTipoProduto,
    descricaoTipoProduto,
    codigoTabelaPreco,
    filial,
    codigoItem,
    precoVenda,
    valorDesconto,
    percentualDesconto,
    ativo,
    frete,
    estado,
    tipoOperacao,
    quantidadeLote,
    indicadorLote,
    moeda,
    dataVigencia,
    referenciaGrade,
    precoMaximo,
    itemGrupo,
    dataUltimaMovimentacao,
    horaUltimaMovimentacao,
    dataExportacaoEC,
    sequenciaExportacaoEC,
    usuarioGeracaoInicial,
    usuarioGeracaoAtualizacao,
    mensagemExportacao,
    horaExportacao,
    envioEC,
    dataAlteracao,
    horaAlteracao,
    horaExportacaoFinal,
    tipoPreco,
    imagens,
    sinalizadores,
    codigoBarraFeiras
  ) 
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
`;
